# Enviornmentals
debug_mode = true
log_level = "Trace"

# Resouce limits
max_ram_usage = 500 # in mb
max_cpu_usage = 15

[git]
default_server = "GitHub"
credentials_file = "/tmp/git.recs"

[aggregator]
socket_path = "/tmp/test.sock"